#!/bin/sh

SEPERATOR="=>"

## Main script ##
echo "	Host => $(cat /etc/hostname)
	User => $USER
 __(.)> Shell => $SHELL
 \__)	WM => $(echo $GDMSESSION)
	Packages => $(pacman -Qq | wc -l)
	Uptime => $(uptime -p | cut -c 4- | sed 's/ //g' | sed 's/,//g' | sed 's/hours/h/g' | sed 's/minutes/m/g')"
