#!/bin/sh

SEPERATOR="=>"
ART="
__(.)>
\__)
"
prin() {
    echo "$1 $2 $SEPERATOR $3"
}

## Main script ##
prin  Host $(cat /etc/hostname)
prin  User $USER
prin  Shell $SHELL
prin  WM $(echo $GDMSESSION)
prin  Packages $(pacman -Qq | wc -l)
prin  Uptime $(uptime -p | cut -c 4- | sed 's/ //g' | sed 's/,//g' | sed 's/hours/h/g' | sed 's/minutes/m/g')
